# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FnF_plugin
                                 A QGIS plugin
 This plugin creates an FnF kwaliteitstoets output
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-07
        copyright            : (C) 2024 by Robin van Maaren
        email                : rvmrobin@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FnF_plugin class from file FnF_plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .FnF_plugin import FnF_plugin
    return FnF_plugin(iface)
